### ISSUE TITLE
Why is Photon Voice used instead of Oculus VoIP?

### ISSUE THREAD

**Issue by DenizBicer** [oculus-samples/Unity-SharedSpaces#1]
Hi Oculus Samples Team,

I am evaluating available SDKs for Networking in Quest. I was considering using [Oculus VoIP](https://developer.oculus.com/documentation/unity/ps-voip/) for voice chat, but in this sample I see that [Photon Voice](https://www.photonengine.com/voice) is used. Is there a reason why the Oculus VoIP is not used? Was it only a practical decision since Photon is already used in Transport Layer for Netcode?

**Comment by jasonmeisel** [comment]
> Was it only a practical decision since Photon is already used in Transport Layer for Netcode?

That is correct - using Photon Voice was the simplest method since the project already relied on Photon.

Another reason is just that Photon Voice is a very popular choice for VR voice chat, in part because it is cross-platform. Since it's already widely used, we wanted to illustrate that it's fully supported on the Quest platform.
