### ISSUE TITLE
apk Upload failed

### ISSUE THREAD

**Issue by mlavinb** [oculus-samples/Unity-SharedSpaces#13]
hello, I followed all the tutorial without errors.
When uploading my .apk file through ODH I get an "upload failed" error message. No more information.
Thank you

**Comment by pr0-zac** [comment]
If you use the [command line utility](https://developer.oculus.com/resources/publish-reference-platform-command-line-utility/) you will get more output about the error.  

I suspect it is failing because the developer dashboard now requires you target Android version 29 or higher. Check Project Settings > Player > Android > Identification > Target API Level. This should be Android 10.0 (API level 29). If not, you may need to install it via Android Studio.

**Comment by mlavinb** [comment]
thank you @pr0-zac 
I couldn't reproduce the error.
I did the tutorial again now using the same version of Unity and the app works on at least 1 Oculus device. I haven't been able to test with multiple users yet.

**Comment by pr0-zac** [comment]
Glad to hear it's working now. I'm going to close this issue. If it happens again, feel free to re-open.
