### ISSUE TITLE
Photon Realtime Transport for Netcode for GameObjects Issues

### ISSUE THREAD

**Issue by adrianktng** [oculus-samples/Unity-SharedSpaces#16]
Follow up from #10.

Updated to the newer version 2.0.1 of "Photon Realtime Transport for Netcode for GameObjects" which removed the issues above but throw in two new errors in Unity 2021.3.10f1.

`Assets\SharedSpaces\Scripts\SharedSpacesSession.cs(28,25): error CS0176: Member 'NetworkManager.ServerClientId' cannot be accessed with an instance reference; qualify it with a type name instead`

`Assets\SharedSpaces\Scripts\SharedSpacesSession.cs(70,23): error CS0176: Member 'NetworkManager.ServerClientId' cannot be accessed with an instance reference; qualify it with a type name instead`

On the other hand, downgrade Netcode for Gameobjects to 1.0.0-pre.5 works without error.

**Comment by AlexThiv** [comment]
In the latest version of Netcode for Gameobjects you will notice that the `NetworkManager.ServerClientId` is now a const. As the error message suggest you can't access it using an instance reference, to fix your issue you can call `NetworkManager.ServerClientId` instead of `NetworkManager.Sigleton.ServerClientId`.

**Comment by AlexThiv** [comment]
Closing issue. If there is still issues, feel free to reopen.
