### ISSUE TITLE
Upload Failed: APK Package Name Error

### ISSUE THREAD

**Issue by SommerChase** [oculus-samples/Unity-SharedSpaces#21]
![image](https://user-images.githubusercontent.com/42384821/228999535-636fb10c-e41e-41cc-85a8-79741f402a85.png)

After building the demo and attempting to upload the .apk to Meta Quest Developer Hub, I am getting the error above.

**Comment by AlexThiv** [comment]
Hi @SommerChase,
Thanks for bringing this up.
It seems like the package name defaults to use "com.oculus" because it was left empty in our repository. Since it's a reserved package name you won't be able to push the apk. You can go into PlayerSettings and changed the package name.

I changed the package name with something that won't cause issues. See [commit](https://github.com/oculus-samples/Unity-SharedSpaces/commit/f0beb58f754b6b83d222b3afdcd8a84fdaa081d3)

**Comment by SommerChase** [comment]
Dope - thanks for the response!
